### ISSUE TITLE
Autosubs error

### ISSUE THREAD

**Issue by chris2677** [amet/service.autosubs#49]
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.autosubs/default.py", line 3, in <module>
                                                       from resources.lib.autosubs import *
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.autosubs/resources/lib/autosubs.py", line 14, in <module>
                                                       __cwd__ = xbmc.translatePath(__addon__.getAddonInfo('path'))
                                                                 ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
[kodi.log](https://github.com/amet/service.autosubs/files/10472551/kodi.log)

**Comment by chris2677** [comment]
After the Kodi 20 update autosubs has this error.
